version: '2'
services:
  blog2-app:
    image: blog2
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://blog2-mysql:3306/blog2?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://blog2-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://blog2-elasticsearch:9200
    ports:
      - 8888:8888
  blog2-mysql:
    extends:
      file: mysql.yml
      service: blog2-mysql
  blog2-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: blog2-elasticsearch
